### ISSUE TITLE
mayusculasNombreCompleto(). Mejora planteada para la clase User.

### ISSUE THREAD

**Issue by vpaniego** [vpaniego/IWVG.SwC.VanesaPaniego#1]
[wiki User](https://github.com/vpaniego/IWVG.SwC.VanesaPaniego/wiki/User)

Hito: 24/09/2018

**Comment by vpaniego** [comment]
Buenas.
He visto que en la implementación de la mejora no se está teniendo en cuenta que 'name' y 'fullName' puedan tener valores null, cadena vacía, o cadena con espacio. En ese caso si pruebas el test falla.

En la mejora se pide que se tenga en cuenta esos casos, tratarlos para poder sacar una traza con el error de "Nombre de usuario desconocido".

Por otro lado, he visto que en el test, se está haciendo una prueba para ver que se devuelve una excepción, pero ésta excepción es de tipo "ArithmeticException" que no se va a producir nunca. 

Cualquier duda me comentas y lo vemos. 
Gracias!

**Comment by lelepompom** [comment]
Hola Vanesa!

1. En la clase User:

Ahora mismo se está teniendo en cuenta que 'format' (por tanto afecta a 'name' y a 'fullname') no puede estar vacío, en ese caso devuelve la excepción 'Nombre de usuario desconocido', y también se asegura que format no sea null. Lo amplío entonces para cadena con espacio.

En la wiki pone "En caso de estar vacío el nombre y el apellido", ¿esto se refiere a lanzar la excepción si name está vacío Y fullname está vacío? ¿O se refiere a lanzar la excepción si name está vacío O fullname está vacío? Entendiendo vacío como: 'null', '""' y '" "'.

Intenté detectar estos valores dentro del método 'mayusculasNombreCompleto' para lanzar la excepción, pero como el contructor pasa tanto 'name' como 'fullname' por 'format' encontré mejor la solución anterior. 

¿Debería hacer la comprobación en el método 'mayusculasNombreCompleto' en lugar de en 'format'?


2. Por otra parte, en la clase UserTest:

- Se hace un test que comprueba que se pasan a mayúsculas tanto 'name' como 'fullname' de un User. 

- Y se hace otro test con el 'name' vacío que comprueba que se lanza una ArithmeticException e imprime en consola el mensaje 'Nombre de usuario desconocido', no veo que no se produzca la excepción? Este segundo test devuleve la misma excepción en el caso de que haya 'name' y no 'fullname' y en el caso en que no haya ninguno de los dos.

Estos dos test se hacen dentro de 'testMayusculasNombreCompleto()'. ¿Debería quizá crear un segundo método para separar los test? En caso afirmativo, ¿cómo querrías que lo llamara?

En relación a lo que comento de la clase User, si se diferencian más casos, ¿qué tests debería hacer?


Perdona por la extensión, pero es que no me ha quedado claro.

Gracias!

**Comment by vpaniego** [comment]
Hola Sandra!

No te preocupes, mejor preguntar que quedarse con la duda.
Espero que ahora me sepa explicar mejor y de esa forma podamos dar por cerrada la mejora.

En cuanto a la clase User:
Tienes razón en cuanto al método format. Me parece perfecto el control en ese método ya que se está llamando desde el constructor. Sería controlar tanto null, cadena vacía y espacio en blanco. Si lo haces de esa manera puedes tratar la excepción en el constructor y evitas crear un objeto incompleto porque alguno de sus valores no es correcto.
En cuanto a la excepción, creo que sería mejor una de tipo IllegalArgumentException ya que alguno de los parámetros no es correcto. Con eso creo que respondo a otra de tus preguntas, con cualquiera de los dos datos a null, vacío o espacio, es incompleto y debería lanzar la excepción con mensaje "Nombre de usuario desconocido".

En cuanto a la clase UserTest:
Es cierto que podía haber especificado mejor el test, lo siento eso fue fallo mío. Me parece correcto que lo separes en dos métodos de test, uno para probar la transformación a mayúsculas y otro para probar que se lanza correctamente la excepción cuando alguno de los parámetros del constructor es incorrecto. 

Puedes llamarlo testMayusculasNombreCompleto_IllegalArgumentException().

Espero haber resuelto las dudas y si no cualquier cosa me dices.

Gracias!

**Comment by lelepompom** [comment]
Genial Vanesa! 
Totalmente de acuerdo, aquí es más apropiado IllegalArgumentException que ArithmeticException. 
He modificado eso y el método String format() para que se lance el mensaje de error en cualquiera de los 3 casos (null, "" y " "). 
En UserTest he dividido las pruebas en 4 tests: el que comprueba que se pone a mayúsculas y 3 que comprueban la excepción, para null, "" y " ".
Ya me dices qué tal esta ahora :)

**Comment by vpaniego** [comment]
Ok. Visto!
Resultado correcto en la ejecución de los test.
Puedes cerrar la tarea porque por mi parte está completa!

Gracias Sandra!!

**Comment by lelepompom** [comment]
Estupendo! Gracias a ti!
