### ISSUE TITLE
Ampliar a tercera coordenada. Mejora en clase Point

### ISSUE THREAD

**Issue by vpaniego** [vpaniego/IWVG.SwC.VanesaPaniego#2]
[wiki Point](https://github.com/vpaniego/IWVG.SwC.VanesaPaniego/wiki/Point)

Hito: 30/09/2018

**Comment by vpaniego** [comment]
Hola Diego!

¿Cómo llevas la tarea? 

Si tienes alguna duda respecto a la ampliación de ésta clase o cualquier comentario que quieras hacer, por favor no dudes en decírmelo y lo vemos.

Un saludo.-
Vanesa

**Comment by DiegoRiofrio** [comment]
Hola Vanesa,

Disculpame, lo que pasa es que no he tenido tiempo entre el trabajo, el examen de mañana y las otras tareas que se entregan mañana y el lunes, :/

En cuanto me pongo ;)

Un saludo

Diego

**Comment by vpaniego** [comment]
Ok Diego perfecto.
Era por saber si tenías alguna duda! Cuando puedas!

Un saludo.-
Vanesa

**Comment by DiegoRiofrio** [comment]
Hola Vanesa,

Ya he terminado la tarea, échale un ojo cuando puedas y si esta todo bien, la cierro.

saludos

Diego Riofrio

**Comment by vpaniego** [comment]
Hola Diego!
Sí, ya he visto los cambios subidos sobre la clase Point y los test ejecutados. Por mi está correcto.

Sólo comentarte una cosa. He visto que no está el método 'unitVector()' supongo que entre todos los cambios que tenías, se te ha pasado. No te preocupes porque he visto que has tenido en cuenta la tercera coordenada en el método 'translateOrigin' que yo al principio dude si pedirte porque era la mejora más amplia de todas las pedidas y creo que de esa forma es más completa la implementación de la clase Point.

Da por cerrada la incidencia indicando que has completado el método translateOrgin y que se deja la ampliación 'unitVector' para una siguiente versión (si la hubiese :)) 

Gracias Diego.

Saludos
Vanesa
